source 'https://rubygems.org'
gem 'calabash-cucumber', '0.20.0'
gem 'calabash-android', '0.8.2'
gem 'xamarin-test-cloud', '2.0.0'
gem 'selenium-webdriver'
gem 'rest-client'
gem 'rspec'
gem 'rspec-expectations'
gem 'spec'
gem 'test-unit'
gem 'pry'

# gem 'appium_console'
# gem 'appium_lib'
